# Generated by Django 2.2.16 on 2022-06-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
