# Generated by Django 2.2.16 on 2022-06-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220601_2213'),
        ('reviews', '0004_remove_user_confirmation_code'),
    ]

    operations = [
    ]
