# Generated by Django 2.2.16 on 2022-06-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220602_2045'),
        ('reviews', '0005_merge_20220602_0445'),
    ]

    operations = [
    ]
