# Generated by Django 2.2.16 on 2022-06-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220603_0558'),
        ('reviews', '0006_auto_20220602_2055'),
    ]

    operations = [
    ]
