# Generated by Django 2.2.16 on 2022-06-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220604_0528'),
        ('reviews', '0011_auto_20220604_1321'),
    ]

    operations = [
    ]
