# Generated by Django 2.2.16 on 2022-06-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20220604_1204'),
        ('reviews', '0011_auto_20220604_0528'),
    ]

    operations = [
    ]
