# Generated by Django 2.2.16 on 2022-06-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220604_1321'),
        ('reviews', '0012_merge_20220604_1834'),
    ]

    operations = [
    ]
