# Generated by Django 2.2.16 on 2022-06-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_merge_20220604_2159'),
        ('reviews', '0013_alter_user_first_name'),
    ]

    operations = [
    ]
