# Generated by Django 2.2.16 on 2022-06-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20220605_0829'),
        ('reviews', '0015_auto_20220606_0120'),
    ]

    operations = [
    ]
