# Generated by Django 2.2.16 on 2022-06-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_merge_20220606_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date', 'id')},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pub_date', 'id')},
        ),
    ]
